<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <style>
        * { font-family: DejaVu Sans, sans-serif; }
        body { color: #111827; font-size: 12px; margin: 0; padding: 24px; }
        .header { border-bottom: 3px solid #047857; padding-bottom: 12px; margin-bottom: 16px; }
        .company { font-size: 20px; font-weight: bold; color: #064e3b; }
        .doc-title { color: #64748b; font-size: 13px; margin-top: 2px; }
        .meta { width: 100%; margin-bottom: 16px; }
        .meta td { padding: 3px 0; vertical-align: top; }
        .meta .label { color: #64748b; width: 120px; }
        .meta .value { font-weight: bold; }
        table.lines { width: 100%; border-collapse: collapse; margin-bottom: 14px; }
        table.lines th { background: #ecfdf5; color: #047857; text-align: left; padding: 6px 8px; font-size: 11px; }
        table.lines td { padding: 6px 8px; border-bottom: 1px solid #e5e7eb; }
        table.lines td.amt { text-align: right; }
        .section-title { font-weight: bold; color: #064e3b; margin: 8px 0 4px; font-size: 12px; }
        .net-box { background: linear-gradient(135deg,#047857,#22c55e); color: #fff; padding: 12px 16px; border-radius: 8px; margin-top: 8px; }
        .net-box .label { font-size: 12px; opacity: .9; }
        .net-box .amount { font-size: 22px; font-weight: bold; }
        .footer { margin-top: 24px; color: #94a3b8; font-size: 10px; text-align: center; }
        .cols { width: 100%; }
        .cols td { width: 50%; vertical-align: top; padding-right: 12px; }
    </style>
</head>
<body>
    <div class="header">
        <div class="company">{{ $company }}</div>
        <div class="doc-title">Payslip — {{ $periodLabel }}</div>
    </div>

    <table class="meta">
        <tr>
            <td class="label">Employee</td>
            <td class="value">{{ $employee['name'] }}</td>
            <td class="label">Employee No</td>
            <td class="value">{{ $employee['employee_number'] }}</td>
        </tr>
        <tr>
            <td class="label">Pay Period</td>
            <td class="value">{{ $periodLabel }}</td>
            <td class="label">Structure</td>
            <td class="value">{{ $structure ?? '—' }}</td>
        </tr>
    </table>

    <table class="cols">
        <tr>
            <td>
                <div class="section-title">Earnings</div>
                <table class="lines">
                    <thead><tr><th>Item</th><th style="text-align:right">Amount</th></tr></thead>
                    <tbody>
                    @foreach ($earnings as $item)
                        <tr><td>{{ $item['name'] }}</td><td class="amt">{{ $item['formatted'] }}</td></tr>
                    @endforeach
                    <tr><td><strong>Gross Pay</strong></td><td class="amt"><strong>{{ $grossFormatted }}</strong></td></tr>
                    </tbody>
                </table>
            </td>
            <td>
                <div class="section-title">Deductions</div>
                <table class="lines">
                    <thead><tr><th>Item</th><th style="text-align:right">Amount</th></tr></thead>
                    <tbody>
                    @forelse ($deductions as $item)
                        <tr><td>{{ $item['name'] }}</td><td class="amt">{{ $item['formatted'] }}</td></tr>
                    @empty
                        <tr><td colspan="2">No deductions</td></tr>
                    @endforelse
                    <tr><td><strong>Total Deductions</strong></td><td class="amt"><strong>{{ $deductionsFormatted }}</strong></td></tr>
                    </tbody>
                </table>
            </td>
        </tr>
    </table>

    <div class="net-box">
        <div class="label">Net Pay</div>
        <div class="amount">{{ $netFormatted }}</div>
    </div>

    <div class="footer">
        Generated by FruitionHR · This payslip is computer-generated from a locked payroll snapshot.
    </div>
</body>
</html>
